/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 cube_queen.glb
Author: Cradle of the Cube (https://sketchfab.com/Observer_Terminator)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cube-queen-c563e640f78c4ac6b67faf6d74ae0193
Title: Cube Queen
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cube_queen(props) {
  const { nodes, materials } = useGLTF('model/cube_queen.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.F_MED_Cube_Queen_Dark_Body} skeleton={nodes.Object_7.skeleton} />
          <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.F_MED_Cube_Queen_Dark_Head} skeleton={nodes.Object_8.skeleton} />
          <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.F_MED_Cube_Queen_Dark_FaceAcc} skeleton={nodes.Object_9.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('model/cube_queen.glb')
